typography_spectrum: 0.3770888026834161
content_rating:
  adult: false
color:
  brandColors:
    - '#0B040C'
    - '#084E06'
    - '#621390'
    - '#FFFAFF'
    - '#6A5888'
  brandStrength: 0.8237504768132757
  lightness: 0.704527032578198
  saturation: 0.0432975276756921
  rhythmicContrast: 0.6994980047393294
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.7890374001117405
analytics:
  google: UA-74195413-1
author:
  name: Davie E Hodge
  url: 'http://www.syftkogtech.com/'
  email: daviehodge@syftkogtech.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0ecc263c-70f1-4c12-89dd-239f300544dd.png
name: syftkogtech.com
cta: {}
navigation:
  - name: More about us ....
    url: 'https://www.linkedin.com/in/davie-hodge-854ba55'
    type: external
  - name: IRS Issues Ransomware Warning
    id: a5362a95-49c3-4fed-884d-87cdad22ad65
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c7f408b5-9fc2-4262-8fa3-06e33ffb82a5.jpg
title: >-
  Our technology experts search the planet for innovative products, and after a
  rigorous evaluation process, we select the best products. The result of our
  work is what you see here.
content: []
purpose: []
