name: syftkogtech.com
favicon: null
layout_spectrum: 0.7250922825187445
typography_spectrum: 0.6797739763278514
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74195413-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5259742089547217
  lightness: 0.24773873947560787
  saturation: 0.8519023407716304
  rhythmicContrast: 0.804760844213888
purpose: []
