layout_spectrum: 0.3811950664609523
typography_spectrum: 0.26446892279375456
color:
  brandColors:
    - '#0B040C'
    - '#084E06'
    - '#621390'
    - '#FFFAFF'
    - '#6A5888'
  brandStrength: 0.0011225980844828162
  lightness: 0.10361773733160284
  saturation: 0.9552634853809739
  rhythmicContrast: 0.011877552451621188
name: syftkogtech.com
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c7f408b5-9fc2-4262-8fa3-06e33ffb82a5.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0ecc263c-70f1-4c12-89dd-239f300544dd.png
cta: {}
analytics:
  google: UA-74195413-1
opengraph:
  type: ''
  appId: ''
purpose:
  - type: internal
    label: IBM Gives cryptocurency Green light For GOVERNMENT USE.
    item: 7a550314-89be-4979-9010-7fc99f46a027
  - type: internal
    label: Data Recovery Specialist
    item: 85b596b1-8331-4fda-b101-c417497c2456
title: >-
  Our technology experts search the planet for innovative products, and after a
  rigorous evaluation process, we select the best products. The result of our
  work is what you see here.
author:
  name: Davie E Hodge
  url: 'http://www.syftkogtech.com/'
  email: daviehodge@syftkogtech.com
content_rating:
  adult: false
navigation:
  - name: More about us ....
    url: 'https://www.linkedin.com/in/davie-hodge-854ba55'
    type: external
  - name: IRS Issues Ransomware Warning
    id: a5362a95-49c3-4fed-884d-87cdad22ad65
    type: content
  - name: Would SeLinux have stopped Equifax Breach ?
    id: ae3690f2-a162-4e1a-a325-b2c42c69bcad
    type: content
  - name: 'Data Recovery Technology '
    id: 85b596b1-8331-4fda-b101-c417497c2456
    type: content
content: []
github: true
