name: syftkogtech.com
favicon: null
layout_spectrum: 0.7250922825187445
typography_spectrum: 0.6797739763278514
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74195413-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#036993'
    - '#8bb4e2'
    - '#111111'
    - '#db8950'
  brandStrength: 0.5259742089547217
  lightness: 0.24773873947560787
  saturation: 0.8519023407716304
  rhythmicContrast: 0.804760844213888
purpose: []
